### PR TITLE
ISSUE-78 [VOBJECT] ITIP for recurrence exceptions

### LINKED ISSUE #78: [VOBJECT] IMIP for recurrence exceptions
CF https://github.com/bastien-roucaries/vobject/commits/waiting-merges-4.2.2/

c0821871acf29e56ceb143d951425257128623cb

Fix occurrence reply handling
   When updating participation (replying) to an occurrence of a recurrent event, the event is duplicated in event owner view.
   The reply in realtime is not transmitted/handled correctly.
   -> The vcalendar contains -n vevents (master & exceptions) while it should contain only the modified exception

Bob creates recurring even (daily, 3 occurrence)
Bob invites Alice to occurence 2 only
Alice ITIP the message
And get things in her calendar
   -> Verify that "WHEN Bob invites Alice to occurence 2 only" sabre handle the correct AMQP message
   -> And verify that TCalendar handles it well

----------------------------------------

e42ac8e142d83118c16175e21f0a2601ca39aa21

Bob creates recurring even (daily, 3 occurrence)
Bob invites Alice to occurence 2 only
If bob modify instance 3 then alice do not receive email
If bob modify instance then alice receive email
If bob cancel "all events" Alice is notified about it
If bob update location (and only location) then alice is notified about it

**Definition of done**
 - Relevant tests in Twake Mail (ITIP processing for recurrence exceptions)
 - Relevant tests in EmailAMQPMessageContract

### PR DESCRIPTION
**Pull request by vttranlina**
resolve https://github.com/linagora/twake-calendar-integration-tests/issues/78

### CODE REVIEW

File: src/test/java/com/linagora/dav/contracts/ITIPRequestContract.java [hunk 1]
```diff
@@ -738,4 +746,715 @@ void itipCancelShouldRemoveInstancesFromRecurringEvent() throws JsonProcessingEx
...
+        Calendar expectedCalendar = CalendarUtil.parseIcsAndSanitize(expectedCalendarIcs);
+
+        // Assert equality (logical content, ignoring order or minor formatting)
+        assertThat(actualCalendar)
+            .as("Cedric's calendar should contain only the invited occurrence (#2), no recurrence rule")
+            .isEqualTo(expectedCalendar);
+    }
+
+    @Test
+    void shouldNotDuplicateEventInOrganizerCalendarAfterSingleOccurrenceReplyOfRecurrenceEvent() {
```
Comment (chibenwa) [inline src/test/java/com/linagora/dav/contracts/ITIPRequestContract.java]: Please add a test 

Given a recurring daily named REC organized by cendrive
WHEN Cedric invites bob to occurence number 2 and bob ITIP the change
AND Cedric invites bob to occurence number 3 and bob ITIP the change
THEN the two events are bundled together in bob calendar

Thanks ;-)

**Comment by vttranlina** [comment]
CI failed with base image `linagora/esn-sabre:sabre-4_1_5-rc5` 
Let me investigate

**Review by chibenwa — APPROVED** [review]
